name: Aws Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - examples/shop/**
      - .github/workflows/aws-static-web-apps-shop.yml

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - examples/shop/**
      - .github/workflows/aws-static-web-apps-shop.yml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build And Deploy
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint:shop

      - name: Test
        run: npm run test:shop

      - name: Build
        run: npm run build:shop

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist/shop # ruta del compilado
          bucket: angular-shop # nombre del bucket creado en aws
          bucket-region: us-east-2 # región con la que configuramos el bucket
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SEA_01B016E10 }}
          action: "close"
